// <auto-generated />
using System;
using ClinicAppointmentsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAppointmentsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115165123_AddDoctorToAppointment")]
    partial class AddDoctorToAppointment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalProblem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2024, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3058),
                            DoctorId = 1,
                            MedicalProblem = "Flu",
                            PatientId = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3058)
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2024, 5, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3060),
                            DoctorId = 2,
                            MedicalProblem = "Dental Pain",
                            PatientId = 2,
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3060)
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2024, 5, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3061),
                            DoctorId = 3,
                            MedicalProblem = "Checkup",
                            PatientId = 3,
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3062)
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2024, 5, 15, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3063),
                            DoctorId = 4,
                            MedicalProblem = "Back Pain",
                            PatientId = 4,
                            Status = 2,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3063)
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2024, 5, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3064),
                            DoctorId = 5,
                            MedicalProblem = "Migraine",
                            PatientId = 5,
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3065)
                        });
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Avaliabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3126),
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3126)
                        },
                        new
                        {
                            Id = 2,
                            AvailableDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3131),
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3131)
                        },
                        new
                        {
                            Id = 3,
                            AvailableDate = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3135),
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3136)
                        },
                        new
                        {
                            Id = 4,
                            AvailableDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3139),
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3140)
                        },
                        new
                        {
                            Id = 5,
                            AvailableDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3143),
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3144)
                        });
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(2971),
                            Name = "Dr. Smith",
                            Specialty = "Cardiology",
                            UpdatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(2998),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3000),
                            Name = "Dr. Johnson",
                            Specialty = "Orthopedics",
                            UpdatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3001),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3003),
                            Name = "Dr. Brown",
                            Specialty = "Neurology",
                            UpdatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3003),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3005),
                            Name = "Dr. Taylor",
                            Specialty = "Dermatology",
                            UpdatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3006),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3007),
                            Name = "Dr. Lee",
                            Specialty = "Pediatrics",
                            UpdatedAt = new DateTime(2024, 11, 15, 11, 51, 23, 520, DateTimeKind.Local).AddTicks(3007),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3031),
                            Email = "john_doe@example.com",
                            Name = "John Doe",
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3032),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3033),
                            Email = "jane_doe@example.com",
                            Name = "Jane Doe",
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3033),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3034),
                            Email = "mark_smith@example.com",
                            Name = "Mark Smith",
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3035),
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3036),
                            Email = "emily_brown@example.com",
                            Name = "Emily Brown",
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(3036),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2870),
                            Email = "admin@example.com",
                            Password = "admin123",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2871),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2872),
                            Email = "john_doe@example.com",
                            Password = "password123",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2873),
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2874),
                            Email = "jane_doe@example.com",
                            Password = "password123",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2874),
                            Username = "jane_doe"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2875),
                            Email = "dr_smith@example.com",
                            Password = "doctor123",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2876),
                            Username = "dr_smith"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2877),
                            Email = "dr_jones@example.com",
                            Password = "doctor123",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 11, 15, 16, 51, 23, 520, DateTimeKind.Utc).AddTicks(2877),
                            Username = "dr_jones"
                        });
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Appointment", b =>
                {
                    b.HasOne("ClinicAppointmentsApi.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Doctor", b =>
                {
                    b.HasOne("ClinicAppointmentsApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicAppointmentsApi.Models.Patient", b =>
                {
                    b.HasOne("ClinicAppointmentsApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
